CREATE TABLE GOAL (ID int NOT NULL auto_increment,NAME varchar(50) NOT NULL,EVENT varchar(50) NOT NULL,HTMLCLASSNAME varchar(50) NOT NULL,PRIMARY KEY (ID));
CREATE TABLE EXPERIMENT (ID int NOT NULL auto_increment,NAME varchar(50) NOT NULL,CSSATTRIBUTEKEY VARCHAR(50) NOT NULL,HTMLCLASSNAME varchar(50) NOT NULL,GOALID INT NOT NULL,PRIMARY KEY (ID));
CREATE TABLE VARIANT (ID int NOT NULL auto_increment,NAME varchar(50) NOT NULL,PERCENTAGE INT NOT NULL,CSSATTRIBUTEVALUE varchar(50) NOT NULL,EXPERIMENTID INT NOT NULL,PRIMARY KEY (ID));
